### ISSUE TITLE
请修复ipv6地址与markdown中emoji语法冲突的问题

### ISSUE THREAD

**Issue by THUzxj** [thu-cs-lab/Router-Lab-Docs#3]
在 软件实验>验收流程 一章多次出现例如`fd00::a:b`的地址，但是markdown会把`:a:`渲染为:a:，难以阅读，例： 
![image](https://user-images.githubusercontent.com/44231913/139578273-b49eb731-87d4-4c40-a8df-2df3eec45c09.png)
经试验，可以把`:a:`全部替换为`:<zero-width space>a:`。

**Comment by jiegec** [comment]
pull requests are welcome
